<?php
/**
 * Created by PhpStorm.
 * User: delepine
 * Date: 19/07/18
 * Time: 10:28
 */

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FichierUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierUploadRepository extends EntityRepository implements Repository
{


    /**
     * @return array|int
     * @throws \Doctrine\DBAL\DBALException
     */
    public function liste()
    {

        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 
                  fu.id AS id,
                  fu.filename AS filename,
                  fu.updated_at AS updated_at,                   
                  fu.filesize AS file_size,
                  fu.path AS path,
                  fu.originalname AS original_name,
                  fu.error_code AS error_code,
                  fu.nb_col_upload_file as nb_col_upload_file,
                  fu.nb_row_upload_file as nb_row_upload_file,
                  fu.nb_row_uploaded as nb_row_uploaded
                FROM fichierUpload fu';

        $statement = $connexion->query($sql);
        return $statement->fetchAll();
    }


}
