<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PraticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PraticienRepository extends EntityRepository implements Repository
{

    /**
     * @return array|int
     * @throws \Doctrine\DBAL\DBALException
     */
    public function liste()
    {

        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 
                  p.nom_prat AS nom_prat,
                  p.prenom_prat AS prenom_prat,                   
                  p.code_praticien AS code_praticien,
                  p.cle_prat AS cle_prat,
                  v.libelle_ville AS libelle_ville,
                  u.code_utaa AS code_utaa                 
                FROM praticien p
                join utaa u on p.utaa_id = u.id
                join ville v on p.ville_id = v.id';

        $statement = $connexion->query($sql);
        return $statement->fetchAll();
    }

}
