<?php

namespace AppBundle\Repository;

use AppBundle\Tools\JsonHandler;
use CNAMTS\PHPK\CoreBundle\Data\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository implements Repository
{

    public function DataHeader()
    {
        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 
                  t.colonne_theme AS colonne_theme                 
                FROM theme t';

        $statement = $connexion->query($sql);

        $dataHeader = $statement->fetchAll();

        return $dataHeader;
    }

    /**
     * @return array|int
     */
    public function liste()
    {
        $session = new Session();

        $em = $this->getEntityManager();
        $theme =
            $em->getRepository('AppBundle:Theme')
                ->findOneBy([

                    'libelleTheme' => $session->get('filenameUpload')


                ]);

        $themeCiblage[] = JsonHandler::mergeData($theme->getColonneTheme(), $theme->getCommentaireColonne());


        return $themeCiblage;

    }

}