<?php

namespace AppBundle\Repository;

/**
 * UtaaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtaaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * requête permettant de récupérer la liste des utaas en fonction de l'id du département.
     * elle est utilisée dans requête ajax pour onglet requête globale
     *
     * @param $idDepartement
     * @return mixed
     */
    public function listUtaasByDepartement($idDepartement){


        $query = $this->createQueryBuilder('u')
            ->select('u.id ')
            ->addSelect('u.codeUtaa')
            ->where('u.departement = :departement')
            ->setParameter('departement', $idDepartement)
            ->getQuery();

        return $query->getResult();
    }
}
