<?php

namespace App\Repository;


/**
 * AgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeRepository extends \Doctrine\ORM\EntityRepository
{


}
