<?php

namespace App\Repository;


use CNAMTS\PHPK\CoreBundle\Data\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends EntityRepository implements Repository
{
    /**
     * Methode du repository qui recupère la liste des periodes de la table periode
     * la méthode liste est utilisée pour l'enrichissement en data de Tableaux/ListePeriodeName.php
     *
     * @return array|int
     * @throws \Doctrine\DBAL\DBALException
     */
    public function liste()
    {

        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 
                  p.id as id,                 
                  p.code AS code,
                  p.annee AS annee,
                  p.is_active AS isActive,
                  p.is_semestre AS isSemestre                              
              FROM periode p
              where isActive= 1
              order by code';

        $statement = $connexion->query($sql);
        return $statement->fetchAll();

    }



}
