<?php
/**
 * Created by PhpStorm.
 * User: delepine
 * Date: 25/10/18
 * Time: 10:11
 */

namespace App\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository implements Repository
{


    /**
     * Methode du repository qui recupère la liste des periodes de la table periode
     * la méthode liste est utilisée pour l'enrichissement en data de Tableaux/Name.php
     *
     * @return array|int
     * @throws \Doctrine\DBAL\DBALException
     */
    public function liste()
    {


        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'SELECT 
                  r.id as id,
                  r.is_active AS isActive,                 
                  r.libelle_region AS libelleRegion                                                
               FROM region r
               where r.libelle_region != "non definie"';

        $statement = $connexion->query($sql);
        return $statement->fetchAll();

    }

    /**
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function departementsEtUtaaRegionActive()
    {

        $connexion = $this->getEntityManager()->getConnection();

        $sql = 'select  
                  distinct d.libelle_dep,
                  u.code_utaa
                from
                  region r 
                join
                  departement d 
                on
                  r.id = d.region_id 
                join 
                  utaa u 
                on
                  d.id = u.departement_id
                where
                  r.is_active=1';

        $statement = $connexion->query($sql);

        return $statement->fetchAll();

    }


}