app_import_fichier_detail:
  path:   /detail/{id}
  defaults: { _controller: 'AppBundle:AdministrationController\Import:detail' }

app_import_fichier_praticiens:
  path:   /praticien
  defaults: { _controller: 'AppBundle:AdministrationController\Import:uploadpraticien' }

app_import_fichier_ciblage:
  path:   /ciblage
  defaults: { _controller: 'AppBundle:AdministrationController\Import:uploadciblage' }

app_import_fichier_delete:
  path:   /{id}/delete
  defaults: { _controller: 'AppBundle:AdministrationController\Import:delete' }

app_import_fichier_liste:
  path:   /liste
  defaults: { _controller: 'AppBundle:AdministrationController\Import:liste' }

app_import_fichier_commentaire:
  path:   /commentaire
  defaults: { _controller: 'AppBundle:AdministrationController\Import:uploadcommentaire' }

