app_requete_globale:
    path: /globale
    defaults: { _controller: 'AppBundle:RequeteController\RequeteGlobale:requeteGlobale' }
    methods: POST|GET

app_requete_praticien:
    path: /praticien
    defaults: { _controller: 'AppBundle:Requete:praticien' }

app_requete_globale_resultat:
    path: /globale/resultat/{periodeId}/{periode}/{themeId}/{depId}/{utaaId}/{ageId}
    defaults: { _controller: 'AppBundle:RequeteController\RequeteGlobale:resultat' }

app_requete_globale_export:
    path: /globale/export/{periode}/{theme}/{dep}/{utaa}/{age}
    defaults: { _controller: 'AppBundle:RequeteController\RequeteGlobale:export' }

utaa_ajax_list_by_departement:
    path: /ajax_utaas
    defaults: { _controller: 'AppBundle:RequeteController\RequeteGlobale:ajaxListUtaaByDepartement'}
    methods: POST|GET
